/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment8;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
String input = "Según un estudio de una universidad inglesa, no importa el orden en el que las letras están escritas, la única cosa importante es que la primera y última letra estén escritas en la posición correcta. El resto pueden estar totalmente mal y aún podrás leerlo sin problemas. Esto es porque no leemos cada letra por sí misma. sino la palabra como un todo. Personalmente me parece increíble.";
Assignment8 d=new Assignment8();
String fin=d.azar(input);
System.out.println(fin);
}
}
